### ISSUE TITLE
Permissions from contract fail with Error 17: execution reverted. 

### ISSUE THREAD

**Issue by nmanchovski** [hyperledger/burrow#1334]
**Describe the Bug**

Permissions from contract as described in fixture app33 evm_connection_edb_permissions_and_roles_layer doesn't work.

In version 0.29.0 the test fail with Error 17: execution reverted: execution reverted. 
As a response on the RPC call I get Permission Denied

In version 0.29.8 the test fail with "cannot map from string to EVM address"
As a response on the RPC call I get Error 17: execution reverted: execution reverted. 

executing sh deploy.sh on a clean checkout reports "Tests complete! Tests are Green. :)", but if you scroll up, you can see errors, thus the script doesn't exit with error if there are failed test cases.

**To Reproduce**

1. Clean checkout of any version > 0.29.0
2. run tests/deploy.sh - test app33-evm_connection_edb_permissions_and_roles_layer  fail

3. Execute Transaction to update base or Role through the native Permission contract -  Error 17: execution reverted: execution reverted / Permission denied

**Expected Behavior**

1. No errors in test cases 
2. Test Execution to fail on failed tests
3. Set base from native permission contract to pass without EVM execution error

**Technical Details**

burrow 0.29.0+commit.v0.29.0+2020-02-14
go version go1.13.4 darwin/amd64

**Comment by silasdavis** [comment]
Thanks very much!

The bug is mine, but more importantly you've found a case where we swallow errors in tests (burrow deploy can exit 0 on multi playbook runs). Should both be fixed in: https://github.com/hyperledger/burrow/pull/1340

**Comment by nmanchovski** [comment]
Thank you for the quick fix @silasdavis! I will try it out in the following days... When do you expect the next release to be published so I can get it in an official docker build?

**Comment by silasdavis** [comment]
@nmanchovski the bug has surfaced some other errors - they shouldn't be hard to fix but I doubt I will get time to work on it until weekend.

I think I'd like to batch together our recent eWASM support a well as fixing this bug and possibly #1342 in `0.30.0` release. I would aim for something early next week.

You can build your own image in the the PR branch (https://github.com/hyperledger/burrow/tree/deploy-errs) by checking it out and running `make docker_build` if you need an image with this fixed sooner.

**Comment by nmanchovski** [comment]
Sounds good... I just saw the test execution and I actually need the fix for this failure which is still being reproduced in the branch https://github.com/hyperledger/burrow/runs/450466085
So I will wait for your updates. 

log_channel=Info message="Playbook result" jobNo=32 file=app33-evm_connection_edb_permissions_and_roles_layer/deploy.yaml error="\nThere has been an error talking to your Burrow chain using account C9F239591C593CB8EE192B0009C6A0F2C9F8D768.\n\nerror 17 - Error 17: execution reverted: call error: error 17 - Error 17: execution reverted: execution reverted\nEVM call trace: Call: C9F239591C593CB8EE192B0009C6A0F2C9F8D768 -> 6673F5A9137DEF3DEB426F16B2446A9A61381208:  [error 17 - Error 17: execution reverted: execution reverted]\n\n" time=2.618922867s
3457

**Comment by nmanchovski** [comment]
For Your information: the tests are still failing, but not reported as errors - I can see the build is green. Could be a failed regression 
Any clues on how to resolve the above issues?

**Comment by silasdavis** [comment]
I have a PR with various of the issues fixed #1340 I just need to find a solid block of time to fix the remaining issues. It is my top priority for Burrow.
